function robot = r_create(theta,d,a,alpha,ndof,types)
% create a robot structure from denavit-hartenberg parameters



r = struct( 'theta', sym(theta), ...
    'd', sym(d), ...
    'a', sym(a), ...
    'alpha', sym(alpha), ...
    'type', char(types), ...
    'ndof',ndof);

robot = r;
end